[package]
name = "wgpu-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bytemuck = "1.10.0"
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui", features = ["winit"] }
egui-winit = { git = "https://github.com/emilk/egui" }
env_logger = "0.9.0"
image = "0.24.2"
log = "0.4.17"
nalgebra-glm = "0.17.0"
pollster = "0.2.5"
raw-window-handle = "0.4.3"
wgpu = "0.13.1"
winit = "0.26.1"

[lib]
name = "support"
path = "src/support/lib.rs"
