[package]
name = "wgpu-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
bmfont = { version = "0.3.3", features = ["serde"] }
bytemuck = "1.10.0"
egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui", features = ["winit"] }
egui-winit = { git = "https://github.com/emilk/egui" }
env_logger = "0.9.0"
gltf = { version = "1.0.0", features = ["names", "KHR_lights_punctual", "KHR_materials_unlit"] }
image = "0.24.2"
lazy_static = "1.4.0"
log = "0.4.17"
legion = "0.4.0"
nalgebra = "0.31.0"
nalgebra-glm = { version = "0.17.0", features = ["convert-bytemuck", "serde-serialize"] }
petgraph = { version = "0.6.2", features = ["serde-1"] }
pollster = "0.2.5"
rapier3d = { version = "0.13.0", features = ["serde-serialize", "wasm-bindgen"] }
raw-window-handle = "0.4.3"
serde = "1.0.138"
wgpu = "0.13.1"
winit = "0.26.1"

[lib]
name = "support"
path = "src/support/lib.rs"
